tag: "1.38.0"
provisionDataStore:
  cassandra: false
allInOne:
  extraEnv:
    - name: QUERY_BASE_PATH
      value: /jaeger
  enabled: true
  ingress: 
    enabled: false
storage:
  type: none
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
extraObjects:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: jaeger
      namespace: jaeger
    spec:
      rules:
      - host: localhost
        http:
          paths:
          - path: /jaeger
            pathType: Prefix
            backend:
              service:
                name: jaeger-query
                port:
                  number: 16686
