---
repositories:
  - name: jenkins
    url: https://charts.jenkins.io
releases:
  - name: jenkins
    chart: jenkins/jenkins
    version: 3.3.21
    namespace: jenkins
    values:
      - "values.yml"
...
