---
rbac:
  create: true
controller:
  image: "dduportal/jenkins-k8s"
  tag: "latest"
  jenkinsUrl: http://localhost
  jenkinsAdminEmail: noreply@localhost.local
  installPlugins: []
  ingress:
    enabled: true
    hostName: localhost
  numExecutors: 0
  executorMode: "EXCLUSIVE"
  sidecars:
    configAutoReload:
      enabled: true
  JCasC:
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "butler"
          name: "Jenkins Admin"
          password: "butler"
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false

...
