---
rbac:
  create: true
  readSecrets: true # Required to allow the plugin kubernetes-credentials-provider to read Kubernetes secrets
controller:
  image: "dduportal/jenkins-k8s"
  tag: "latest"
  imagePullPolicy: "IfNotPresent" # Avoid Always if you use an image built locally and loaded in k3d from the local cache
  jenkinsUrl: http://localhost
  jenkinsAdminEmail: noreply@localhost.local
  installPlugins: []
  ingress:
    enabled: true
    hostName: localhost
  numExecutors: 0
  executorMode: "EXCLUSIVE"
  sidecars:
    configAutoReload:
      enabled: true
  JCasC:
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "butler"
          name: "Jenkins Admin"
          password: "butler"
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false
    configScripts:
      pipeline-library: |
        unclassified:
          globalLibraries:
            libraries:
              - defaultVersion: "master"
                implicit: true
                name: "pipeline-library"
                retriever:
                  modernSCM:
                    scm:
                      git:
                        id: "github-access-token"
                        remote: "https://github.com/jenkins-infra/pipeline-library.git"

      jobs: |
        jobs:
          - script: >
              multibranchPipelineJob('docker-builder') {
                displayName "docker-builder"
                branchSources {
                  github {
                    id('2020120401')
                    repoOwner('dduportal')
                    repository('docker-builder')
                    buildForkPRHead(true)
                    buildForkPRMerge(true)
                    buildOriginBranch(true)
                  }
                }
                factory {
                  workflowBranchProjectFactory {
                    scriptPath('Jenkinsfile_k8s')
                  }
                }
                // don't keep build jobs for deleted branches
                orphanedItemStrategy {
                  discardOldItems {
                    numToKeep(-1)
                  }
                }
              }
...
