jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "butler"
  authorizationStrategy: loggedInUsersCanDoAnything
unclassified:
  location:
    url: "http://localhost:8080/"
  openTelemetry:
    authentication: "noAuthentication"
    disabledResourceProviders: "io.opentelemetry.sdk.extension.resources.ProcessResourceProvider"
    endpoint: "http://jaeger:4317"
    exportOtelConfigurationAsEnvironmentVariables: false
    ignoredSteps: "dir,echo,isUnix,pwd,properties"
    observabilityBackends:
    - jaeger:
        jaegerBaseUrl: "http://localhost:16686"
    serviceName: "jenkins"
    serviceNamespace: "jenkins"
  timestamper:
    allPipelines: true
