jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "butler"
  authorizationStrategy: loggedInUsersCanDoAnything
unclassified:
  location:
    url: "http://localhost:8080/"
  # timestamper:
  #   allPipelines: true
