---
repositories:
  - name: jenkins
    url: https://charts.jenkins.io
  - name: jenkins-infra
    url: https://jenkins-infra.github.io/helm-charts
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts
  - name: elastic
    url: https://helm.elastic.co
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  # - name: jenkins-jobs
  #   namespace: jenkins-infra
  #   chart: jenkins-infra/jenkins-jobs
  #   version: 0.3.2
  #   values:
  #     - "values/jenkins-jobs.yaml"
  - name: jenkins-infra
    chart: jenkins/jenkins
    version: 4.1.16
    namespace: jenkins-infra
    values:
      - "values/jenkins.yaml"
    # needs:
    #   - jenkins-jobs # Required to generate the job definition in a configmap
  # - name: jaeger
  #   chart: ./jaegertracing-helm-charts/charts/jaeger
  #   namespace: jaeger
  #   values:
  #     - "values/jaeger.yaml"
