---
repositories:
  - name: jenkins
    url: https://charts.jenkins.io
  - name: jenkins-infra
    url: https://jenkins-infra.github.io/helm-charts
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts
  - name: elastic
    url: https://helm.elastic.co
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: grafana
    url: https://github.com/grafana/helm-charts/
releases:
  # - name: jenkins-jobs
  #   namespace: jenkins
  #   chart: jenkins-infra/jenkins-jobs
  #   version: 0.3.2
  #   values:
  #     - "values/jenkins-jobs.yaml"
  - name: jenkins
    chart: jenkins/jenkins
    version: 4.2.5
    namespace: jenkins
    values:
      - "values/jenkins.yaml"
    # needs:
    #   - jenkins-jobs # Required to generate the job definition in a configmap
  # - name: jaeger
  #   chart: ./jaegertracing-helm-charts/charts/jaeger
  #   namespace: jaeger
  #   values:
  #     - "values/jaeger.yaml"

  # adding grafana support issue #2
  - name: grafana
    chart: grafana/grafana
    namespace: grafana
    values:
      - "values/grafana.yaml"