---
rbac:
  create: true
  readSecrets: true # Required to allow the plugin kubernetes-credentials-provider to read Kubernetes secrets
controller:
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"
    requests:
      cpu: "1"
      memory: "2Gi"
  healthProbes: false
  javaOpts: >-
    -XshowSettings:vm
    -XX:+UseStringDeduplication
    -XX:+ParallelRefProcEnabled
    -XX:+DisableExplicitGC
    -XX:MaxRAM=4g
    -XX:+AlwaysPreTouch
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/tmp/
    -XX:+UseG1GC
    -Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator.websocketConnectionTimeout=60
  jenkinsUrl: http://localhost
  jenkinsAdminEmail: noreply@localhost.local
  installPlugins: false
  ingress:
    enabled: true
    hostName: localhost
  sidecars:
    configAutoReload:
      enabled: true
  JCasC:
    configScripts:
      auth: |
        jenkins:
          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false
          securityRealm:
            local:
              allowsSignup: false
              enableCaptcha: false
              users:
              - id: "butler"
                name: "Jenkins Admin"
                password: "butler"
      advisor-settings: |
        jenkins:
          disabledAdministrativeMonitors:
            - com.cloudbees.jenkins.plugins.advisor.Reminder
      system-settings: |
        unclassified:
          defaultFolderConfiguration:
            healthMetrics:
            # Keep healthMetrics an empty list to ensure weather is disabled
            healthMetrics: []
        jenkins:
          quietPeriod: 0 # No need to wait between build scheduling
          disabledAdministrativeMonitors:
            - "jenkins.security.QueueItemAuthenticatorMonitor"
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                - gitHubApp:
                    appID: "${GITHUB_APP_ID}"
                    description: "GitHub App for infra.ci.jenkins.io"
                    id: "github-app-infra"
                    privateKey: "${GITHUB_APP_PRIVATE_KEY}"
                    scope: GLOBAL
                    owner: "dduportal"
